apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaml-k8-deployment                            
spec:                                        
  selector:
    matchLabels:
      app: yaml-k8-app
  replicas: 1
  template:
    # kind: Pod
    metadata:
      labels: 
        app: yaml-k8-app
    spec:
      containers:
        - name: yaml-k8-cnt
          image: amoghnagar123/k8app


